### ISSUE TITLE
WMS 1.3.0 is required

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/sdi-consistence-check#1]
We depend on https://github.com/geopython/OWSLib/pull/334 being merged for true INSPIRE compatibility. By default, WMS capabilities are currently 1.1.1

**Comment by Vampouille** [comment]
geopython/OWSLib#334 seem to be merged with https://github.com/geopython/OWSLib/pull/343

**Comment by fvanderbiest** [comment]
... and it was merged ! \o/
