### ISSUE TITLE
Handle OWSlib FutureWarning

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/sdi-consistence-check#2]
Querying https://www.ppige-npdc.fr/geoserver/wms ...
/usr/local/lib/python3.5/site-packages/owslib/iso.py:111: FutureWarning: the .identification and .serviceidentification properties will merge into .identification being a list of properties.  This is currently implemented in .identificationinfo.  Please see https://github.com/geopython/OWSLib/issues/38 for more information
  FutureWarning)
/usr/local/lib/python3.5/site-packages/owslib/iso.py:451: FutureWarning: The .keywords and .keywords2 properties will merge into the .keywords property in the future, with .keywords becoming a list of MD_Keywords instances. This is currently implemented in .keywords2. Please see https://github.com/geopython/OWSLib/issues/301 for more information

**Comment by fvanderbiest** [comment]
This is an annoying warning in the command output...
I tried redirecting stderr to /dev/null but no luck with that.

**Comment by pmauduit** [comment]
see 878d300d0dcdf7de449face3d54e69a655ef0f65
