### ISSUE TITLE
Automated docker image builds

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/sdi-consistence-check#27]
https://hub.docker.com/r/georchestra/sdi-consistence-check/ should build the image for this repository every time a commit is pushed.

**Comment by pmauduit** [comment]
@fvanderbiest this one can be closed ? seems that something / someone regenerated the docker images after my last commit, relying on the repository on docker-hub

**Comment by fvanderbiest** [comment]
> seems that something / someone regenerated the docker images after my last commit, relying on the repository on docker-hub

Yes, travis does the job.
