### ISSUE TITLE
[WMS check] cannot check GeoServer workspace ?

### ISSUE THREAD

**Issue by MaelREBOUX** [georchestra/sdi-consistence-check#35]
It seems not possible to perform a check in WMS mode on a workspace.

```
python checker.py --mode WMS --server https://portail-test.sig.rennesmetropole.fr/geoserver/ladm_terri/wms/ --disable-ssl-verification

SDI check
mode: WMS
WxS service URL: https://portail-test.sig.rennesmetropole.fr/geoserver/ladm_terri/wms/
output mode: log

0 layers parsed, 0 inconsistencies found (0 %)
```

From a web browser we retrieve the WMS capacity service document and the layer exists.

https://portail-test.sig.rennesmetropole.fr/geoserver/ladm_terri/ows?service=wms&request=GetCapabilities

**Comment by pmauduit** [comment]
Just added some code to handle the implicit workspace prefix.

**Comment by catmorales** [comment]
python checker.py --mode WMS --server https://portail-test.sig.rennesmetropole.fr/geoserver/ladm_terri/wms/ --disable-ssl-verification
Traceback (most recent call last):
  File "checker.py", line 9, in <module>
    from owslib.util import ServiceException
ImportError: No module named owslib.util

**Comment by catmorales** [comment]
sorry bas cut/paste

**Comment by pmauduit** [comment]
on portail-test, you need to use the python3 installed in /usr/local:

```
/usr/local/bin/python3.4 checker.py --mode WMS --server https://portail-test.sig.rennesmetropole.fr/geoserver/ladm_terri/wms/ --disable-ssl-verification
```

**Comment by catmorales** [comment]
Yes, it's better 
we have really 11 layers in this workspace .
 Result is:
```
 /usr/local/bin/python3.4 checker.py --mode WMS --server https://portail-test.sig.rennesmetropole.fr/geoserver/ladm_terri/wms/ --disable-ssl-verification

SDI check


mode: WMS

WxS service URL: https://portail-test.sig.rennesmetropole.fr/geoserver/ladm_terri/wms/
output mode: log

start time: 2017-04-06 11:55:05



#0
  Layer: TOP25_
  Error: No metadata defined for layer TOP25_



11 layers parsed, 1 inconsistencies found (9 %)
end time: 2017-04-06 11:55:13
```

**Comment by catmorales** [comment]
ok c'est bon pour nous
