### ISSUE TITLE
Déplacer vers georchestra/sdi-consistence-check ?

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/sdi-consistence-check#4]
Au vu de la portée du développement, est-ce que Rennes Métropole accepterait de déplacer ce dépot vers l'organisation https://github.com/georchestra/sdi-consistence-check ?

**Comment by catmorales** [comment]
Oui pas de problèmes , si on peut figurer en tant que financeurs dans le fichier readme ça serait top !

**Comment by fvanderbiest** [comment]
Super !
Evidemment, pas de problèmes pour vous mettre comme financeurs dans le README :-)

Pour organiser le transfert, il faudrait me définir comme administrateur (au moins temporairement) de l'organisation github `sigrennesmetropole`. Merci !

**Comment by catmorales** [comment]
C'est fait !
Dis moi quand tu auras fini, je te remettrai "member".
Catherine

De : François Van Der Biest [mailto:notifications@github.com]
Envoyé : lundi 19 septembre 2016 15:12
À : sigrennesmetropole/sdi-consistence-check
Cc : MORALES Catherine; Assign
Objet : Re: [sigrennesmetropole/sdi-consistence-check] Déplacer vers georchestra/sdi-consistence-check ? (#4)


Super !
Evidemment, pas de problèmes pour vous mettre comme financeurs dans le README :-)

Pour organiser le transfert, il faudrait me définir comme administrateur (au moins temporairement) de l'organisation github sigrennesmetropole. Merci !

**Comment by fvanderbiest** [comment]
All done :-)
