### ISSUE TITLE
WMS1.3.0 GetCapabilities - parsing styles block without a title element fails

### ISSUE THREAD

**Issue by pmauduit** [georchestra/sdi-consistence-check#5]
GeoServer can under certain circumstances produce a WMS 1.3 getcapabilities with style blocks which has no title (which is not wms1.3.0-compliant):

https://github.com/highsource/jsonix/blob/master/demos/wms/src/main/resources/wms/1.3.0/capabilities_1_3_0.xsd#L510-L529

This is IMHO a bug in GeoServer (at least an empty element `<Title/>` should be produced in the getcapabilities), but it makes the GetCapabilities parsing from OWSLib fail.

Either way the lib is too pedantic for our expected usage and will need a better error handling, or we need to address the issue geoserver-side. I'm a bit puzzled.

**Comment by pmauduit** [comment]
After exchanging with @Vampouille, we are thinking of a "scenario 0", where  a first XSD validation is made onto the GetCapabilities. If this validation fails, there is no need to go further into owslib.

I don't know yet if it will be necessary for other protocols (WFS/CSW) though.

**Comment by fvanderbiest** [comment]
> GeoServer can under certain circumstances produce a WMS 1.3 getcapabilities with style blocks which has no title (which is not wms1.3.0-compliant):

Maybe we can request full CITE compatibility in GeoServer UI...
![capture du 2016-09-28 11 19 55](https://cloud.githubusercontent.com/assets/265319/18907831/83b4a114-856d-11e6-8709-eebc4237005e.png)

**Comment by pmauduit** [comment]
By reading the GS code I don't think it will fix it

**Comment by MaelREBOUX** [comment]
I confirm : it is the Title which causes the bug.

```xml
  <NamedLayer>
    <se:Name>espub_dech:v_gesbac_pav</se:Name>
    <UserStyle>
      <se:Name>v_gesbac_pav_pnt</se:Name>
        <se:Description>
          <!--<se:Title>Style par défaut</se:Title>-->
          <se:Abstract>Style par défaut</se:Abstract>
        </se:Description>
```

**Comment by pmauduit** [comment]
Workaround proposed here:
https://github.com/georchestra/geoserver/pull/6

**Comment by fvanderbiest** [comment]
> Workaround proposed here:

Merged.
GeoServer to be recompiled & redeployed.

**Comment by MaelREBOUX** [comment]
The @pmauduit PR has been closed and not merged.
I had not seen antother PR from pmauduit.

So GeoServer master has not been patched ?

**Comment by pmauduit** [comment]
> So GeoServer master has not been patched ?


Here is the status: geOr PR has been merged ; upstream PR, I never had the time to propose something better (i.e. with unit tests) to the GS community.

**Comment by MaelREBOUX** [comment]
OK it is what I have understand :
- GeoServer 2.8.3 geOrchestra master / 16.12 patched
- GeoServer master / 2.11 not patched

So in the future if we update the version of GeoServer (neeed...) we will know this bug too.

What to do : close this issue and open a new on to not forget ?

**Comment by fvanderbiest** [comment]
Time (=funding) is required to get the fix into geoserver master.
That's all I can say here.

**Comment by MaelREBOUX** [comment]
How to do to not lost this issue for GeoServer master and close this issue here ?

**Comment by geojs** [comment]
> How to do to not lost this issue for GeoServer master and close this issue here ?

Add a new PR to fix into GeoServer master:
https://github.com/geoserver/geoserver/pull/2200

**Comment by MaelREBOUX** [comment]
You rocks @geojs ! Thank you.
