### ISSUE TITLE
Implement a xunit output

### ISSUE THREAD

**Issue by pmauduit** [georchestra/sdi-consistence-check#53]
See https://en.wikipedia.org/wiki/XUnit#Test_result_formatter, or https://gist.github.com/jperras/882006 ; having this kind of output format could make it very interesting to plug the scripts into Jenkins, to get a graphical view after run.

**Comment by pmauduit** [comment]
Tried to implement on WMS / WFS check on georhena gives the following output (once both xml files have been processed using `junit-viewer` npm package): https://sdi-stable.georchestra.org/~pmauduit/georhena.html

**Comment by MaelREBOUX** [comment]
Not a bad idea.

Colours in your example are quite agressive. No ?

**Comment by pmauduit** [comment]
It was just to test the report output, actually my idea is to use the Jenkins junit report module so that we use the Jenkins UI.
