### ISSUE TITLE
[all mode] Missing metadata title

### ISSUE THREAD

**Issue by pmauduit** [georchestra/sdi-consistence-check#9]
in the mode CSW output:

```
UUID: <uuid>
```

It would be nice to print the MD title next to the uuid

**Comment by pmauduit** [comment]
`checker.py:82`:

cswq.get_records() could return a tuple (uuid, title), instead of only the uuid

**Comment by MaelREBOUX** [comment]
needed for #13 and #14

**Comment by MaelREBOUX** [comment]
Done for me ?

**Comment by MaelREBOUX** [comment]
nope : see #30 and #31 (work in progress)
